/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "surface-tint": "#1261a3",
        "on-surface": "#0D1321",
        "surface-variant": "#e1e2e8",
        "on-secondary-fixed-variant": "#004f4f",
        "surface-bright": "#f8f9ff",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "tertiary": "#6a3100",
        "status-approved": "#2E7D32",
        "outline": "#727781",
        "status-pending": "#F9A825",
        "surface-container-low": "#f2f3f9",
        "outline-variant": "#c1c7d2",
        "surface-background": "#F2F4F7",
        "on-error": "#ffffff",
        "on-surface-variant": "#414750",
        "on-primary-container": "#afd1ff",
        "on-secondary-container": "#007070",
        "tertiary-fixed": "#ffdcc7",
        "on-tertiary-fixed": "#311300",
        "secondary-fixed": "#8cf3f3",
        "on-primary-fixed-variant": "#00487f",
        "on-tertiary-container": "#ffc29c",
        "on-tertiary-fixed-variant": "#733600",
        "primary": "#00B4FF",
        "status-off": "#757575",
        "surface-container-highest": "#e1e2e8",
        "secondary-container": "#7B5CFF",
        "surface-container": "#ecedf4",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eff0f7",
        "surface-container-high": "#e7e8ee",
        "surface-border": "#E2E8F0",
        "primary-container": "#00B4FF",
        "inverse-primary": "#a1c9ff",
        "status-denied": "#D32F2F",
        "surface": "#f8f9ff",
        "on-secondary-fixed": "#002020",
        "tertiary-fixed-dim": "#ffb787",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3035",
        "primary-fixed": "#d2e4ff",
        "surface-dim": "#d8dae0",
        "tertiary-container": "#8d4401",
        "secondary-fixed-dim": "#6fd7d6",
        "primary-fixed-dim": "#a1c9ff",
        "on-background": "#0D1321",
        "surface-container-lowest": "#ffffff",
        "secondary": "#7B5CFF",
        "on-primary-fixed": "#001c37",
        "on-secondary": "#ffffff",
        "background": "#f8f9ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "row-height-dense": "40px",
        "grid-gutter": "1px",
        "container-padding": "24px",
        "sidebar-width": "260px",
        "base": "8px"
      },
      fontFamily: {
        "h2": ["Inter"],
        "body-md": ["Inter"],
        "h3": ["Inter"],
        "body-lg": ["Inter"],
        "h1": ["Inter"],
        "label-sm": ["Inter"],
        "data-tabular": ["Inter"]
      },
      fontSize: {
        "h2": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "h3": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "h1": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "data-tabular": ["13px", {"lineHeight": "1.2", "fontWeight": "500"}]
      }
    }
  },
  plugins: [],
}
